/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package examenii_p2_rodrigovasquez;

import java.io.*;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.TreeNode;

/**
 *
 * @author Rui
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pp_periodo = new javax.swing.JPopupMenu();
        jmi_agregarDeporte = new javax.swing.JMenuItem();
        pp_deporte = new javax.swing.JPopupMenu();
        jmi_agregarTorneo = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jmi_guardarBinario = new javax.swing.JMenuItem();
        pp_torneo = new javax.swing.JPopupMenu();
        jmi_agregarPartido = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jmi_agregarEquipo = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jmi_listarEquipos = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jmi_tablaPosiciones = new javax.swing.JMenuItem();
        jd_agregarPartido = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        cb_equipo1 = new javax.swing.JComboBox<>();
        cb_equipo2 = new javax.swing.JComboBox<>();
        sp_equipo1 = new javax.swing.JSpinner();
        sp_equipo2 = new javax.swing.JSpinner();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jd_agregarDeporte = new javax.swing.JDialog();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tf_nombreDeporte = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jd_agregarTorneo = new javax.swing.JDialog();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tf_nombreTorneo = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jd_agregarEquipo = new javax.swing.JDialog();
        jPanel7 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tf_nombreEquipo = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jd_listarEquipos = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jl_equipos = new javax.swing.JList<>();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jt_partidos = new javax.swing.JTable();
        jd_tablaPosiciones = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_torneos = new javax.swing.JTree();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jmi_agregarDeporte.setText("Agregar Deporte");
        jmi_agregarDeporte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmi_agregarDeporteMouseClicked(evt);
            }
        });
        jmi_agregarDeporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_agregarDeporteActionPerformed(evt);
            }
        });
        pp_periodo.add(jmi_agregarDeporte);

        jmi_agregarTorneo.setText("Agregar Torneo");
        jmi_agregarTorneo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_agregarTorneoActionPerformed(evt);
            }
        });
        pp_deporte.add(jmi_agregarTorneo);
        pp_deporte.add(jSeparator4);

        jmi_guardarBinario.setText("Guardar en Binario");
        jmi_guardarBinario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_guardarBinarioActionPerformed(evt);
            }
        });
        pp_deporte.add(jmi_guardarBinario);

        jmi_agregarPartido.setText("Agregar Partido");
        jmi_agregarPartido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmi_agregarPartidoMouseClicked(evt);
            }
        });
        jmi_agregarPartido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_agregarPartidoActionPerformed(evt);
            }
        });
        pp_torneo.add(jmi_agregarPartido);
        pp_torneo.add(jSeparator1);

        jmi_agregarEquipo.setText("Agregar Equipo");
        jmi_agregarEquipo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmi_agregarEquipoMouseClicked(evt);
            }
        });
        jmi_agregarEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_agregarEquipoActionPerformed(evt);
            }
        });
        pp_torneo.add(jmi_agregarEquipo);
        pp_torneo.add(jSeparator2);

        jmi_listarEquipos.setText("Listar Equipos");
        jmi_listarEquipos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_listarEquiposActionPerformed(evt);
            }
        });
        pp_torneo.add(jmi_listarEquipos);
        pp_torneo.add(jSeparator3);

        jmi_tablaPosiciones.setText("Tabla de Posiciones");
        pp_torneo.add(jmi_tablaPosiciones);

        jPanel3.setBackground(new java.awt.Color(255, 204, 255));

        cb_equipo1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N

        cb_equipo2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N

        sp_equipo1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        sp_equipo1.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        sp_equipo2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        sp_equipo2.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        jButton1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButton1.setText("Registrar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Equipo #1");

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Equipo #2");

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("< PARTIDO >");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(sp_equipo1)
                            .addComponent(cb_equipo1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cb_equipo2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sp_equipo2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(38, 38, 38))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(62, 62, 62))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(142, 142, 142))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_equipo1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_equipo2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sp_equipo2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sp_equipo1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout jd_agregarPartidoLayout = new javax.swing.GroupLayout(jd_agregarPartido.getContentPane());
        jd_agregarPartido.getContentPane().setLayout(jd_agregarPartidoLayout);
        jd_agregarPartidoLayout.setHorizontalGroup(
            jd_agregarPartidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jd_agregarPartidoLayout.setVerticalGroup(
            jd_agregarPartidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel6.setBackground(new java.awt.Color(95, 235, 130));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Nombre:");

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("[ DEPORTE ]");

        jButton4.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButton4.setText("GUARDAR");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_nombreDeporte, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(97, 97, 97))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(tf_nombreDeporte, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton4)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jd_agregarDeporteLayout = new javax.swing.GroupLayout(jd_agregarDeporte.getContentPane());
        jd_agregarDeporte.getContentPane().setLayout(jd_agregarDeporteLayout);
        jd_agregarDeporteLayout.setHorizontalGroup(
            jd_agregarDeporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jd_agregarDeporteLayout.setVerticalGroup(
            jd_agregarDeporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel5.setBackground(new java.awt.Color(228, 228, 58));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Nombre:");

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("~ TORNEO ~");

        jButton3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButton3.setText("GUARDAR");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(86, 86, 86))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_nombreTorneo, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(16, Short.MAX_VALUE))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                    .addComponent(tf_nombreTorneo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jd_agregarTorneoLayout = new javax.swing.GroupLayout(jd_agregarTorneo.getContentPane());
        jd_agregarTorneo.getContentPane().setLayout(jd_agregarTorneoLayout);
        jd_agregarTorneoLayout.setHorizontalGroup(
            jd_agregarTorneoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jd_agregarTorneoLayout.setVerticalGroup(
            jd_agregarTorneoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel7.setBackground(new java.awt.Color(228, 228, 58));

        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Nombre:");

        jLabel11.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("{ EQUIPO }");

        jButton5.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButton5.setText("GUARDAR");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_nombreEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(107, 107, 107))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(tf_nombreEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton5)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jd_agregarEquipoLayout = new javax.swing.GroupLayout(jd_agregarEquipo.getContentPane());
        jd_agregarEquipo.getContentPane().setLayout(jd_agregarEquipoLayout);
        jd_agregarEquipoLayout.setHorizontalGroup(
            jd_agregarEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jd_agregarEquipoLayout.setVerticalGroup(
            jd_agregarEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(76, 255, 255));

        jl_equipos.setModel(new DefaultListModel());
        jl_equipos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_equiposMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jl_equipos);

        jLabel12.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("|| EQUIPOS ||");

        jt_partidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Equipo #1", "Equipo #2", "Goles Equipo #1", "Goles Equipo #2"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jt_partidos);
        if (jt_partidos.getColumnModel().getColumnCount() > 0) {
            jt_partidos.getColumnModel().getColumn(0).setResizable(false);
            jt_partidos.getColumnModel().getColumn(1).setResizable(false);
            jt_partidos.getColumnModel().getColumn(2).setResizable(false);
            jt_partidos.getColumnModel().getColumn(3).setResizable(false);
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 870, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(468, 468, 468)
                .addComponent(jLabel12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );

        javax.swing.GroupLayout jd_listarEquiposLayout = new javax.swing.GroupLayout(jd_listarEquipos.getContentPane());
        jd_listarEquipos.getContentPane().setLayout(jd_listarEquiposLayout);
        jd_listarEquiposLayout.setHorizontalGroup(
            jd_listarEquiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jd_listarEquiposLayout.setVerticalGroup(
            jd_listarEquiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(76, 255, 255));

        jLabel13.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("<< TABLA DE POSICIONES >>");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Equipo", "Partidos Jugados", "Partidos Ganados", "Empates", "Partidos Perdidos", "Goles a Favor", "Goles en Contra", "Puntos"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(0).setResizable(false);
            jTable2.getColumnModel().getColumn(1).setResizable(false);
            jTable2.getColumnModel().getColumn(2).setResizable(false);
            jTable2.getColumnModel().getColumn(3).setResizable(false);
            jTable2.getColumnModel().getColumn(4).setResizable(false);
            jTable2.getColumnModel().getColumn(4).setHeaderValue("Partidos Perdidos");
            jTable2.getColumnModel().getColumn(5).setResizable(false);
            jTable2.getColumnModel().getColumn(5).setHeaderValue("Goles a Favor");
            jTable2.getColumnModel().getColumn(6).setResizable(false);
            jTable2.getColumnModel().getColumn(6).setHeaderValue("Goles en Contra");
            jTable2.getColumnModel().getColumn(7).setResizable(false);
            jTable2.getColumnModel().getColumn(7).setHeaderValue("Puntos");
        }

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 1188, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addGap(335, 335, 335))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout jd_tablaPosicionesLayout = new javax.swing.GroupLayout(jd_tablaPosiciones.getContentPane());
        jd_tablaPosiciones.getContentPane().setLayout(jd_tablaPosicionesLayout);
        jd_tablaPosicionesLayout.setHorizontalGroup(
            jd_tablaPosicionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jd_tablaPosicionesLayout.setVerticalGroup(
            jd_tablaPosicionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(220, 91, 91));

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Torneos");
        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Q1");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Q2");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Q4");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Q5");
        treeNode1.add(treeNode2);
        jt_torneos.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jt_torneos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jt_torneosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jt_torneos);

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("<  UNITEC >");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/examenii_p2_rodrigovasquez/jaguares.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(23, 23, 23))
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(134, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jt_torneosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jt_torneosMouseClicked
        if (evt.isMetaDown()) {
            int row = jt_torneos.getClosestRowForLocation(evt.getX(), evt.getY());
            jt_torneos.setSelectionRow(row);
            Object v1 = jt_torneos.getSelectionPath().getLastPathComponent();
            nodo_seleccionado = (DefaultMutableTreeNode) v1;
            DefaultTreeModel model = (DefaultTreeModel) jt_torneos.getModel();
            if (nodo_seleccionado.getUserObject() instanceof Deporte) {
                pp_deporte.show(evt.getComponent(), evt.getX(), evt.getY());
            } else if (nodo_seleccionado.getUserObject() instanceof String) {
                pp_periodo.show(evt.getComponent(), evt.getX(), evt.getY());
            } else if (nodo_seleccionado.getUserObject() instanceof Torneo) {
                pp_torneo.show(evt.getComponent(), evt.getX(), evt.getY());
            }
        }
    }//GEN-LAST:event_jt_torneosMouseClicked

    private void jmi_agregarPartidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmi_agregarPartidoMouseClicked
        abrir(jd_agregarPartido);
    }//GEN-LAST:event_jmi_agregarPartidoMouseClicked

    private void jmi_agregarEquipoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmi_agregarEquipoMouseClicked
        abrir(jd_agregarEquipo);
    }//GEN-LAST:event_jmi_agregarEquipoMouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        boolean newDeporte = true;
        for (Deporte deporte : deportes) {
            if (deporte.getNombre().equals(tf_nombreDeporte.getText())) {
                newDeporte = false;
            }
        }
        if (newDeporte) {
            deportes.add(new Deporte(tf_nombreDeporte.getText()));
            DefaultTreeModel modelo = (DefaultTreeModel) jt_torneos.getModel();
            DefaultMutableTreeNode root = (DefaultMutableTreeNode) modelo.getRoot();
            DefaultMutableTreeNode nodo1 = (DefaultMutableTreeNode) root.getChildAt(0);
            nodo1.add(new DefaultMutableTreeNode(new Deporte(tf_nombreDeporte.getText())));
            DefaultMutableTreeNode nodo2 = (DefaultMutableTreeNode) root.getChildAt(1);
            nodo2.add(new DefaultMutableTreeNode(new Deporte(tf_nombreDeporte.getText())));
            DefaultMutableTreeNode nodo3 = (DefaultMutableTreeNode) root.getChildAt(2);
            nodo3.add(new DefaultMutableTreeNode(new Deporte(tf_nombreDeporte.getText())));
            DefaultMutableTreeNode nodo4 = (DefaultMutableTreeNode) root.getChildAt(3);
            nodo4.add(new DefaultMutableTreeNode(new Deporte(tf_nombreDeporte.getText())));
            modelo.reload();
            tf_nombreDeporte.setText("");
            JOptionPane.showMessageDialog(jd_agregarDeporte, "Se ha agregado el deporte", "ADD_SUCCESSFUL", JOptionPane.INFORMATION_MESSAGE);
            jd_agregarDeporte.setVisible(false);
        } else {
            JOptionPane.showMessageDialog(jd_agregarDeporte, "Ese deporte ya existe", "NOMBRE_INVALIDO", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton4MouseClicked

    private void jmi_agregarDeporteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmi_agregarDeporteMouseClicked
        abrir(jd_agregarDeporte);
    }//GEN-LAST:event_jmi_agregarDeporteMouseClicked

    private void jmi_agregarDeporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_agregarDeporteActionPerformed
        abrir(jd_agregarDeporte);
    }//GEN-LAST:event_jmi_agregarDeporteActionPerformed

    private void jmi_agregarTorneoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_agregarTorneoActionPerformed
        abrir(jd_agregarTorneo);
    }//GEN-LAST:event_jmi_agregarTorneoActionPerformed

    private void jmi_agregarPartidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_agregarPartidoActionPerformed
        DefaultTreeModel modelo = (DefaultTreeModel) jt_torneos.getModel();
        DefaultMutableTreeNode root = (DefaultMutableTreeNode) modelo.getRoot();
        cb_equipo1.removeAllItems();
        cb_equipo2.removeAllItems();
        if (nodo_seleccionado.getChildCount() > 1) {
            for (Equipo equipo : equipos) {
                cb_equipo1.addItem(equipo.getNombre());
                cb_equipo2.addItem(equipo.getNombre());
            }
            abrir(jd_agregarPartido);
            DefaultComboBoxModel modeloCb1 = (DefaultComboBoxModel) cb_equipo1.getModel();
        } else {
            JOptionPane.showMessageDialog(pp_torneo, "No se puede crear partidos sin tener al menos dos equipos", "EQUIPOS_INSUFICIENTE", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_jmi_agregarPartidoActionPerformed

    private void jmi_agregarEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_agregarEquipoActionPerformed
        abrir(jd_agregarEquipo);
    }//GEN-LAST:event_jmi_agregarEquipoActionPerformed

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        boolean newTorneo = true;
        for (Torneo torneo : torneos) {
            if (torneo.getNombre().equals(tf_nombreTorneo.getText())) {
                newTorneo = false;
            }
        }
        if (newTorneo) {
            torneos.add(new Torneo(tf_nombreTorneo.getText()));
            DefaultTreeModel modelo = (DefaultTreeModel) jt_torneos.getModel();
            DefaultMutableTreeNode root = (DefaultMutableTreeNode) modelo.getRoot();
            nodo_seleccionado.add(new DefaultMutableTreeNode(new Torneo(tf_nombreTorneo.getText())));
            modelo.reload();
            tf_nombreTorneo.setText("");
            JOptionPane.showMessageDialog(jd_agregarDeporte, "Se ha agregado el torneo", "ADD_SUCCESSFUL", JOptionPane.INFORMATION_MESSAGE);
            jd_agregarTorneo.setVisible(false);
        } else {
            JOptionPane.showMessageDialog(jd_agregarTorneo, "Ese torneo ya existe", "NOMBRE_INVALIDO", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        boolean newEquipo = true;
        for (Equipo equipo : equipos) {
            if (equipo.getNombre().equals(tf_nombreEquipo.getText())) {
                newEquipo = false;
            }
        }
        if (newEquipo) {
            equipos.add(new Equipo(tf_nombreEquipo.getText(), 0));
            JOptionPane.showMessageDialog(jd_agregarEquipo, "Se ha agregado el equipo", "ADD_SUCCESSFUL", JOptionPane.INFORMATION_MESSAGE);
            tf_nombreEquipo.setText("");
            jd_agregarEquipo.setVisible(false);
        } else {
            JOptionPane.showMessageDialog(jd_agregarEquipo, "Ese equipo ya existe", "NOMBRE_INVALIDO", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        if (cb_equipo1.getSelectedItem().equals(cb_equipo2.getSelectedItem())) {
            JOptionPane.showMessageDialog(jd_agregarPartido, "Tiene que elegir equipos diferentes", "INVALID_TEAMS", JOptionPane.ERROR_MESSAGE);
        } else {
            partidos.add(new Partido(cb_equipo1.getSelectedItem().toString(), cb_equipo2.getSelectedItem().toString(), Integer.parseInt(sp_equipo1.getValue().toString()), Integer.parseInt(sp_equipo2.getValue().toString())));
            nodo_seleccionado.add(new DefaultMutableTreeNode(new Partido(cb_equipo1.getSelectedItem().toString(), cb_equipo2.getSelectedItem().toString(), Integer.parseInt(sp_equipo1.getValue().toString()), Integer.parseInt(sp_equipo2.getValue().toString()))));
            Torneo torneo_seleccionado = (Torneo) nodo_seleccionado.getUserObject();
            for (Torneo torneo : torneos) {
                if (torneo.equals(torneo_seleccionado)) {
                    torneo.getPartidos().add(new Partido(cb_equipo1.getSelectedItem().toString(), cb_equipo2.getSelectedItem().toString(), Integer.parseInt(sp_equipo1.getValue().toString()), Integer.parseInt(sp_equipo2.getValue().toString())));
                }
            }
            JOptionPane.showMessageDialog(jd_agregarPartido, "Se ha agregado el partido", "ADD_SUCCESSFUL", JOptionPane.INFORMATION_MESSAGE);
            sp_equipo1.setValue(0);
            sp_equipo2.setValue(0);
            jd_agregarPartido.setVisible(false);
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void jmi_listarEquiposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_listarEquiposActionPerformed
        DefaultListModel modelo = (DefaultListModel) jl_equipos.getModel();
        modelo.removeAllElements();
        for (Equipo equipo : equipos) {
            modelo.addElement(equipo);
        }
        jl_equipos.setModel(modelo);
        
        abrir(jd_listarEquipos);
    }//GEN-LAST:event_jmi_listarEquiposActionPerformed

    private void jmi_guardarBinarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_guardarBinarioActionPerformed
        JFileChooser jfc = new JFileChooser();
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Deporte", "rui");
        jfc.setFileFilter(filtro);
        int seleccion = jfc.showSaveDialog(this);
        FileOutputStream fw = null;
        ObjectOutputStream bw = null;
        if (seleccion == JFileChooser.APPROVE_OPTION) {
            try {
                File file = null;
                if (jfc.getFileFilter().getDescription().equals("Deporte")) {
                    file = new File(jfc.getSelectedFile().getPath() + ".rui");
                } else {
                    file = jfc.getSelectedFile();
                }

                fw = new FileOutputStream(file);
                bw = new ObjectOutputStream(fw);
                bw.writeObject(nodo_seleccionado.getUserObject());
                bw.flush();

                JOptionPane.showMessageDialog(this, "Archivo guardado exitosamente");
            } catch (Exception e) {
            }
        }
        try {
            bw.close();
            fw.close();
        } catch (IOException ex) {
        }
    }//GEN-LAST:event_jmi_guardarBinarioActionPerformed

    private void jl_equiposMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_equiposMouseClicked
        if (evt.getSource() instanceof Equipo) {
            DefaultTableModel modelo = (DefaultTableModel) jt_partidos.getModel();
            
        }
    }//GEN-LAST:event_jl_equiposMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cb_equipo1;
    private javax.swing.JComboBox<String> cb_equipo2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JTable jTable2;
    private javax.swing.JDialog jd_agregarDeporte;
    private javax.swing.JDialog jd_agregarEquipo;
    private javax.swing.JDialog jd_agregarPartido;
    private javax.swing.JDialog jd_agregarTorneo;
    private javax.swing.JDialog jd_listarEquipos;
    private javax.swing.JDialog jd_tablaPosiciones;
    private javax.swing.JList<String> jl_equipos;
    private javax.swing.JMenuItem jmi_agregarDeporte;
    private javax.swing.JMenuItem jmi_agregarEquipo;
    private javax.swing.JMenuItem jmi_agregarPartido;
    private javax.swing.JMenuItem jmi_agregarTorneo;
    private javax.swing.JMenuItem jmi_guardarBinario;
    private javax.swing.JMenuItem jmi_listarEquipos;
    private javax.swing.JMenuItem jmi_tablaPosiciones;
    private javax.swing.JTable jt_partidos;
    private javax.swing.JTree jt_torneos;
    private javax.swing.JPopupMenu pp_deporte;
    private javax.swing.JPopupMenu pp_periodo;
    private javax.swing.JPopupMenu pp_torneo;
    private javax.swing.JSpinner sp_equipo1;
    private javax.swing.JSpinner sp_equipo2;
    private javax.swing.JTextField tf_nombreDeporte;
    private javax.swing.JTextField tf_nombreEquipo;
    private javax.swing.JTextField tf_nombreTorneo;
    // End of variables declaration//GEN-END:variables

    DefaultMutableTreeNode nodo_seleccionado;

    ArrayList<Equipo> equipos = new ArrayList();
    ArrayList<Partido> partidos = new ArrayList();
    ArrayList<Deporte> deportes = new ArrayList();
    ArrayList<Torneo> torneos = new ArrayList();

    public void abrir(javax.swing.JDialog dialog) {
        dialog.setModal(true);
        dialog.pack();
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
    }

}
